baseURL = "/"
relativeURLs = "true"
title = "Photon OS"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["photon-theme"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

 # First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[outputs]
home = [ "HTML", "JSON" ]
page = [ "HTML" ]
section = [ "HTML", "RSS", "print"]

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Additional menu items

[[menu.main]]
    name = "Home"
    weight = 10
    url = "/"

[[menu.main]]
    name = "Features"
    weight = 15
    url = "#features"    

[[menu.main]]
    name = "Docs"
    weight = 20
    url = "/docs/"

[[menu.main]]
    name = "Github"
    weight = 30
    url = "https://github.com/vmware/photon"

[[menu.main]]
    name = "Contribute"
    weight = 20
    url = "#contributing"


[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = ""
description = "VMware Photon docs"
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

[params]

project = "Photon OS"
copyright = "Photon OS Authors."
privacy_policy = "https://vmware.com/help/privacy"

vmw_gh_link ="https://vmware.github.io"

vmw_link = "https://www.vmware.com"

# Dark Mode button (incomplete for now, so just a placeholder)
darkmode = false

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Release"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "v4"


# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "/docs/"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/vmware/photon"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/vmware/photon"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = "example-lander-site"

# for Prod we use gh-pages
github_branch = "gh-pages"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
# Sections to publish in the main RSS feed.
rss_sections = ["blog"]

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = ""

# Enable Algolia DocSearch
algolia_docsearch = false

#Enable offline search with Lunr.js
offlineSearch = true
offlineSearchSummaryLength = 70
offlineSearchMaxResults = 10

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true


# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
# Update with your own repository and response text.
yes = 'Glad to hear it! Please <a href="https://github.com/vmware/photon/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/vmware/photon/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.ui.footer_about_disable]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
# [[params.links.user]]
# 	name ="Twitter"
# 	url = "#"
# 	icon = "fab fa-twitter"
#         desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "GitHub"
	url = "https://github.com/vmware/photon#readme"
	icon = "fab fa-github"
        desc = "We Love GitHub!"
[[params.links.user]]
	name = "Slack"
	url = "https://vmwarecode.slack.com"
	icon = "fab fa-slack"
        desc = "Join the VMware {code} Slack community!"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/vmware/photon"
	icon = "fab fa-github"
        desc = "We Love GitHub!"
# [[params.links.developer]]
	# name = "Slack"
	# url = "https://example.org/slack"
	# icon = "fab fa-slack"
        # desc = "Chat with other project developers"
# [[params.links.developer]]
	# name = "Developer mailing list"
	# url = "https://example.org/mail"
	# icon = "fa fa-envelope"
        # desc = "Discuss development issues around the project"

# mermaidJS is for making flow charts out of markdown
[params.mermaid]
enable = false
theme = "default"

[params.print]
disable_toc = false

[[params.versions]]
  version = "v4 - Latest"
  url = "/docs/"

[[params.versions]]
  version = "v3"
  url = "/docs-v3/"

[[params.versions]]
  version = "v3 (old)"
  url = "/assets/files/html/3.0/"

[[params.versions]]
  version = "v2 and v1"
  url = "/assets/files/html/1.0-2.0/"

[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "printview"
permalinkable = false